FROM golang:1.16-alpine3.12 AS builder

RUN go version

COPY . /script-shell-bot/
WORKDIR /script-shell-bot/

RUN go mod download
RUN GOOS=linux go build -o ./.bin/bot ./cmd/bot/main.go

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /script-shell-bot/.bin/bot .
COPY --from=builder /script-shell-bot/configs .

EXPOSE 80

CMD ["./bot"]