telegramToken: <telegram token secret>

#sudo chat id for send info
sudoChatId: 0

scripts:
  test: "echo 'sega mega test'"
  test2: "shutdown -P 0"

messages:
  response:
    start: "Бот запущен"
    finish: "Бот остановлен"
    help: "Текущий чат ID: %s\n Список доступных команд:\n%s"
  error:
    unknownCommand: "Я не знаю такой команды :("
    default: "Произошла неизвестная ошибка. "

#show debug log
debug: false
